[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

ignored_error_codes = [
    5159 # selfdestruct warning. We are not going deprecate it.
]

[fmt]
bracket_spacing = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config